### ISSUE TITLE
Please add #queryCircle(lat, lon, radius)

### ISSUE THREAD

**Issue by revington** [kuzzleio/boost-geospatial-index#14]
The idea is that given a set of points,shapes,...  you could search for "what is inside the circle".

**Comment by Aschen** [comment]
You can already do that with the `geoDistance` clause https://docs.kuzzle.io/core/2/api/koncorde-filters-syntax/clauses/#geodistance

Is it what you were thinking about?

**Comment by revington** [comment]
He @Aschen,
That is what I'm looking for but I don't know how to achieve that with this library. I'm using this library on a proyect not related to Kuzzle and this library just exposes `#queryPoint(lat, lon)` and `#queryIntersects(points)`

**Comment by Aschen** [comment]
Oh yes you are right! 

I'm pretty you can do it because Koncorde is doing it, have a look:
 - https://github.com/kuzzleio/koncorde/blob/master/lib/engine/storeOperands.ts#L293
 - https://github.com/kuzzleio/koncorde/blob/master/lib/engine/storeOperands.ts#L342
