### ISSUE TITLE
build fails with node 12.0.0, previous deprecation warnings now errors

### ISSUE THREAD

**Issue by markamccann** [kuzzleio/boost-geospatial-index#3]
Previous deprecation warnings regarding 'Utf8Value' that appeared up until node 11.14, are now errors in node 12.0

For example, in 11.4 this warning:
```
./src/spatialIndex.cc:240:25: warning: 'Utf8Value' is deprecated: Use Isolate version
      [-Wdeprecated-declarations]
  v8::String::Utf8Value id(info[0]);
```
is now this error with node 12.0:
```
../src/spatialIndex.cc:240:25: error: no matching constructor for initialization of
      'v8::String::Utf8Value'
  v8::String::Utf8Value id(info[0]);
```

OS is: macOS Mojave

**Comment by markamccann** [comment]
This should be an easy fix since there are only 5 occurrences of Utf8Value:
```./src/spatialIndex.cc:62:  v8::String::Utf8Value argId(info[0]);
./src/spatialIndex.cc:99:  v8::String::Utf8Value argId(info[0]);
./src/spatialIndex.cc:133:  v8::String::Utf8Value argId(info[0]);
./src/spatialIndex.cc:167:  v8::String::Utf8Value argId(info[0]);
./src/spatialIndex.cc:240:  v8::String::Utf8Value id(info[0]);
```

**Comment by scottinet** [comment]
@markamccann > I'm very sorry I didn't see that issue earlier. I came here because of that problem and I'm about to release a new version of this library.

**Comment by markamccann** [comment]
Thanks!  And thank you for making this nice wrapper for this boost library.

**Comment by scottinet** [comment]
Version 1.0.5 fixes the problem.
